# Generated by Django 4.0 on 2021-12-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='shiptype',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='plink',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='pstock',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterModelTable(
            name='detailmodel',
            table='Detail',
        ),
        migrations.AlterModelTable(
            name='ordermodel',
            table='Order',
        ),
        migrations.AlterModelTable(
            name='productmodel',
            table='Product',
        ),
    ]
