# Generated by Django 4.0 on 2021-12-26 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0002_ordermodel_shiptype_productmodel_plink_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='shiptype',
        ),
    ]
