# Generated by Django 4.0 on 2022-01-01 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0003_remove_ordermodel_shiptype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailmodel',
            old_name='pname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='detailmodel',
            old_name='dorder',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='detailmodel',
            old_name='dtotal',
            new_name='total',
        ),
    ]
