# Generated by Django 4.0.1 on 2022-01-11 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0008_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=50),
        ),
    ]
