# Generated by Django 4.0.1 on 2022-01-11 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0009_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailmodel',
            old_name='name',
            new_name='customname',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='pdescription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='pimages',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='plink',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='pname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='pprice',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='pstock',
            new_name='stock',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
