# Generated by Django 4.0.1 on 2022-01-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0011_userprofile_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default='', max_length=50, verbose_name='Phone'),
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table=None,
        ),
    ]
