# Generated by Django 4.0.1 on 2022-01-14 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0012_alter_userprofile_id_alter_userprofile_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='UserProfile',
        ),
    ]
