# Generated by Django 4.2.13 on 2024-07-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0014_alter_userprofile_options_remove_userprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='', max_length=100, verbose_name='Email'),
        ),
    ]
