# Generated by Django 4.2.13 on 2024-07-04 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0020_rename_customname_detailmodel_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='subtotal',
        ),
    ]
