# Generated by Django 4.2.13 on 2024-07-06 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cartapp', '0021_remove_ordermodel_subtotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='description',
            new_name='prod_description',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='images',
            new_name='prod_img',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='link',
            new_name='prod_link',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='name',
            new_name='prod_name',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='price',
            new_name='prod_price',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='username',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='stock',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='prod_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='grandtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.DeleteModel(
            name='DetailModel',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartapp.ordermodel'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartapp.productmodel'),
        ),
    ]
