# Generated by Django 4.2.13 on 2024-07-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0022_orderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('cart', 'In Cart'), ('ordered', 'Ordered')], default='cart', max_length=10),
        ),
    ]
